# Generated by Django 4.1.2 on 2023-02-13 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='имя категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('header_text', models.CharField(max_length=3000)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото поста')),
                ('content', models.TextField(blank=True, verbose_name='Текст поста')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания поста')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения поста')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('name_button_next', models.CharField(default='Читать далее', max_length=40)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='it_projects.category', verbose_name='Категория поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-time_create', 'title'],
            },
        ),
    ]
