# Generated by Django 4.1.2 on 2023-02-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_projects', '0002_alter_projects_header_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='header_text',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
